# Generated by Django 4.2.1 on 2023-06-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_remove_product_created_by_product_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='profile',
            new_name='created_by',
        ),
    ]
