# Generated by Django 4.2.1 on 2023-06-17 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0015_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
